### ISSUE TITLE
How to share a file with java object created with jdx to Java application?

### ISSUE THREAD

**Issue by leobeeson** [floidgilbert/jdx#3]
Hi,

Forgive me if this question sounds too basic, but I'm unable to properly frame my problem in google in order to get some bearings on what to do, or if I'm even doing something terribly silly.

I've produced a matrix in R which a colleague needs to use in a java application. I have already passed him the matrix as a .csv and as a .mtx file, but I'm experimenting if it's possible to send him a serialized java object which he can simply consume directly without much overhead on his end.

I went through [jdx's vignette](https://cran.r-project.org/web/packages/jdx/vignettes/Introduction.html) but couldn't find insights into how to actually share the objects created.

Following [this](https://www.rforge.net/doc/packages/rJava/jserialize.html), I tried the following example:
```
library(rJava)
library(jdx)
m <- matrix(1:9, nrow = 3, ncol = 3)
mj <- convertToJava(m)
mjs <- jserialize(mj)
```
But I get:

> Error in jserialize(mj) : could not find function "jserialize"

My question is then, considering my R service is not currently integrated with my colleagues java application, **how can I share a jclass object created with convertToJava with him?**

Also, please feel free to bash me if this is a silly approach to solve this problem and if there's maybe a more efficient/traditional approach to go about this.

**Comment by floidgilbert** [comment]
Thank you for your question. You are very close; just need to put a period in front of `jserialize`. (It's rJava's unconventional naming scheme..). With that said, I still suggest using CSV or JSON for simple data sharing unless you have a specific reason to do otherwise.
